NUMPY = NUMERICAL PYTHON

In [ ]:
import numpy as np
sales=np.array([22,44,56,78,90])
print(sales)

[22 44 56 78 90]


In [ ]:
import numpy as np
sales=np.array([22,44,56,78,90])
print(sales.size)
print(sales.shape)


5
(5,)


In [ ]:
import numpy as np
prod_price = np.array([120,610,405,320])
print(prod_price)

[120 610 405 320]


In [ ]:
marks=np.array([[22,44,55,66],[88,99,99,99],[67,89,76,90]])

print(marks)            # Provide Data as it is

print(marks.ndim)       # Provide Dimensions of Data set

print(marks.shape)      # Provide the data in matrix form like 3 rows and 4 columns

print(marks.size)       # provide the numbers stored in dataset

print(marks.dtype)      # provide data type

print(marks>55)         # provide true and false values

print(marks[marks>55])  # provide the marks which are greater than 55 (display those which satisfy the condition)


[[22 44 55 66]
 [88 99 99 99]
 [67 89 76 90]]
2
(3, 4)
12
int64
[[False False False  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[66 88 99 99 99 67 89 76 90]


PANDAS - ITS IS A LIBRARY

In [ ]:
import pandas as pd

s1 = pd.Series([10,17,26,35,49,58,77])      # S should be capital

print(s1)

0    10
1    17
2    26
3    35
4    49
5    58
6    77
dtype: int64


In [ ]:
import pandas as pd

s1 = pd.Series([10.1,17.3,26.7,35.5,49,58,77])

print(s1)

0    10.1
1    17.3
2    26.7
3    35.5
4    49.0
5    58.0
6    77.0
dtype: float64


In [ ]:
import pandas as pd
results = pd.Series([70,63,77,56,89,92], index = ["Maths", "English", "Hindi", "Science", "Social", "Computer"])

print(results)

Maths       70
English     63
Hindi       77
Science     56
Social      89
Computer    92
dtype: int64


In [ ]:
s=[100,200,300,400,500,600,700]
day=["Mon","Tues","Wed","Thur","Fri","Sat","Sun"]
Sales=pd.Series(s,index=day)
print(Sales["Tues"])

200


In [ ]:
s=[100,200,300,400,500,600,700]
day=["Mon","Tues","Wed","Thur","Fri","Sat","Sun"]

Sales=pd.Series(s,index=day)

day_input = input('Enter a day name (e.g., Mon, Tues): ')

if day_input in day:
    print("Sales for", day_input, "=", Sales[day_input])
else:
    print('Invalid day')


Enter a day name (e.g., Mon, Tues): Fri
Sales for Fri = 500


In [ ]:
s=[100,200,300,400,500,600,700]
day=["Mon","Tues","Wed","Thur","Fri","Sat","Sun"]
Sales=pd.Series(s,index=day)
day_input = input('Enter a day name (e.g., Mon, Tues): ')
p_day = day_input.title()
if p_day in day:
    print('Sales for', p_day, "=", Sales[p_day])
else:
    print('Invalid day')

Enter a day name (e.g., Mon, Tues): sun
Sales for Sun = 700


In [ ]:
import pandas as pd
s = [100,200,300,400,500,600,700]
day = ["Mon","Tues","Wed","Thur","Fri","Sat","Sun"]
Sales = pd.Series(s, index=day)
user_day = input("Enter day name: ")
if user_day in day:
  print("Sales on", user_day, "=", Sales[user_day])
else:
  print("Invalid day")

Enter day name: Thur
Sales on Thur = 400


In [ ]:
from typing import ValuesView
import numpy as np
s=[100,np.nan,300,400,500,np.nan,700]
day=["Mon","Tues","Wed","Thur","Fri","Sat","Sun"]
Sales=pd.Series(s,index=day)

print(Sales["Tues"])

print(Sales)

print(Sales.isnull())               # Give trues and false Values

print(Sales.isnull().sum())         # give count of NULL Values

print(Sales.notnull())             # Give trues and false Values

print(Sales.notnull().sum())        # give count of NOT NULL Values

print(Sales.dropna())              # Drop NULL Values

print(Sales.fillna(0))            # Fill the null values with bracket value

print(Sales.fillna(Sales.min()))   # fill the null values by min of sales figures

print(Sales.fillna(Sales.max()))   # fill the null values by max of sales figures

print(Sales.fillna(Sales.mean()))  # fill the null values by average of sales figures

nan
Mon     100.0
Tues      NaN
Wed     300.0
Thur    400.0
Fri     500.0
Sat       NaN
Sun     700.0
dtype: float64
Mon     False
Tues     True
Wed     False
Thur    False
Fri     False
Sat      True
Sun     False
dtype: bool
2
Mon      True
Tues    False
Wed      True
Thur     True
Fri      True
Sat     False
Sun      True
dtype: bool
5
Mon     100.0
Wed     300.0
Thur    400.0
Fri     500.0
Sun     700.0
dtype: float64
Mon     100.0
Tues      0.0
Wed     300.0
Thur    400.0
Fri     500.0
Sat       0.0
Sun     700.0
dtype: float64
Mon     100.0
Tues    100.0
Wed     300.0
Thur    400.0
Fri     500.0
Sat     100.0
Sun     700.0
dtype: float64
Mon     100.0
Tues    700.0
Wed     300.0
Thur    400.0
Fri     500.0
Sat     700.0
Sun     700.0
dtype: float64
Mon     100.0
Tues    400.0
Wed     300.0
Thur    400.0
Fri     500.0
Sat     400.0
Sun     700.0
dtype: float64


In [ ]:
import pandas as pd

users={"Name":["ajay","sachin","jay","asha","ekta"],
       "Email":["ajay@gmail.com","sachin@gmail.com","jay@gmail.com","asha@gmail.com","ekta@gmail.com"],
       "Password":["ajay123","sachin123","jay123","asha123","ekta123"],
       "Department":["Admin","sales","marketing","sales","billing"],
       "Salary":[20000,40000,70000,8000,10000]}

df=pd.DataFrame(users)
print(df)

print(df['Department'])

print(df[["Name"], ["Salary"], ["Department"]])

     Name             Email   Password Department  Salary
0    ajay    ajay@gmail.com    ajay123      Admin   20000
1  sachin  sachin@gmail.com  sachin123      sales   40000
2     jay     jay@gmail.com     jay123  marketing   70000
3    asha    asha@gmail.com    asha123      sales    8000
4    ekta    ekta@gmail.com    ekta123    billing   10000
0        Admin
1        sales
2    marketing
3        sales
4      billing
Name: Department, dtype: object


InvalidIndexError: (['Name'], ['Salary'], ['Department'])

In [ ]:
import pandas as pd

users={"Name":["ajay","sachin","jay","asha","ekta"],
       "Email":["ajay@gmail.com","sachin@gmail.com","jay@gmail.com","asha@gmail.com","ekta@gmail.com"],
       "Password":["ajay123","sachin123","jay123","asha123","ekta123"],
       "Department":["Admin","sales","marketing","sales","billing"],
       "Salary":[20000,40000,70000,8000,10000]}

df=pd.DataFrame(users)
print(df)

print(df['Department'])

print(df[["Name", "Salary", "Department"]])

     Name             Email   Password Department  Salary
0    ajay    ajay@gmail.com    ajay123      Admin   20000
1  sachin  sachin@gmail.com  sachin123      sales   40000
2     jay     jay@gmail.com     jay123  marketing   70000
3    asha    asha@gmail.com    asha123      sales    8000
4    ekta    ekta@gmail.com    ekta123    billing   10000
0        Admin
1        sales
2    marketing
3        sales
4      billing
Name: Department, dtype: object
     Name  Salary Department
0    ajay   20000      Admin
1  sachin   40000      sales
2     jay   70000  marketing
3    asha    8000      sales
4    ekta   10000    billing


In [ ]:
import pandas as pd

users={"Name":["ajay","sachin","jay","asha","ekta"],
       "Email":["ajay@gmail.com","sachin@gmail.com","jay@gmail.com","asha@gmail.com","ekta@gmail.com"],
       "Password":["ajay123","sachin123","jay123","asha123","ekta123"],
       "Department":["Admin","sales","marketing","sales","billing"],
       "Salary":[20000,40000,70000,8000,10000]}

Age = [22,35,27,42,37]

df=pd.DataFrame(users)

df["Age"]=Age                             # Add Column

print(df)

df["Bonus"]=df["Salary"]*15/100

print(df)

df["Total Salry"]=df['Bonus']+df['Salary']

print(df)

     Name             Email   Password Department  Salary  Age
0    ajay    ajay@gmail.com    ajay123      Admin   20000   22
1  sachin  sachin@gmail.com  sachin123      sales   40000   35
2     jay     jay@gmail.com     jay123  marketing   70000   27
3    asha    asha@gmail.com    asha123      sales    8000   42
4    ekta    ekta@gmail.com    ekta123    billing   10000   37
     Name             Email   Password Department  Salary  Age    Bonus
0    ajay    ajay@gmail.com    ajay123      Admin   20000   22   3000.0
1  sachin  sachin@gmail.com  sachin123      sales   40000   35   6000.0
2     jay     jay@gmail.com     jay123  marketing   70000   27  10500.0
3    asha    asha@gmail.com    asha123      sales    8000   42   1200.0
4    ekta    ekta@gmail.com    ekta123    billing   10000   37   1500.0
     Name             Email   Password Department  Salary  Age    Bonus  \
0    ajay    ajay@gmail.com    ajay123      Admin   20000   22   3000.0   
1  sachin  sachin@gmail.com  sachin123  

In [ ]:
print(df[df['Department']=="billing"]['Email'])

print(df[df['Department']=="Admin"][['Email', "Password"])



In [ ]:
print(df[ (df['Department']=="Admin")   &   (df['Salary']>20000 ) ])

In [ ]:
print(df[ (df['Department']=="Admin")   |   (df['Salary']>20000 ) ])

In [ ]:
import pandas as pd

data = {
    "Loan_ID": [
        1001, 1002, 1003, 1004, 1005,
        1006, 1007, 1008, 1009, 1010,
        1011, 1012, 1013, 1014, 1015,
        1016, 1017, 1018, 1019, 1020
    ],

    "Applicant_Name": [
        "Rahul Sharma", "Priya Verma", "Amit Kumar", "Neha Singh", "Rohan Mehta",
        "Anjali Gupta", "Vikas Yadav", "Sneha Kapoor", "Arjun Malhotra", "Pooja Jain",
        "Karan Patel", "Simran Kaur", "Manish Sharma", "Ritika Joshi", "Aditya Rao",
        "Nisha Agarwal", "Suresh Kumar", "Meena Rani", "Varun Gupta", "Kavita Singh"
    ],

    "Age": [
        28, 35, 42, 31, 29,
        45, 38, 27, 33, 40,
        36, 30, 48, 26, 34,
        39, 44, 32, 37, 41
    ],

    "Gender": [
        "Male", "Female", "Male", "Female", "Male",
        "Female", "Male", "Female", "Male", "Female",
        "Male", "Female", "Male", "Female", "Male",
        "Female", "Male", "Female", "Male", "Female"
    ],

    "Income": [
        45000, 60000, 75000, 52000, 48000,
        90000, 68000, 42000, 80000, 55000,
        72000, 65000, 95000, 40000, 70000,
        58000, 85000, 50000, 78000, 62000
    ],

    "Loan_Amount": [
        250000, 400000, 600000, 300000, 275000,
        800000, 500000, 200000, 650000, 350000,
        550000, 450000, 900000, 180000, 500000,
        375000, 700000, 280000, 620000, 420000
    ],

    "Loan_Term": [
        5, 10, 15, 7, 5,
        20, 15, 5, 20, 10,
        15, 10, 20, 5, 15,
        10, 20, 7, 15, 10
    ],

    "Credit_Score": [
        720, 680, 750, 690, 710,
        800, 740, 650, 780, 700,
        730, 690, 810, 640, 760,
        710, 790, 675, 745, 700
    ],

    "Employment_Type": [
        "Salaried", "Self-Employed", "Salaried", "Salaried", "Business",
        "Salaried", "Business", "Salaried", "Salaried", "Self-Employed",
        "Salaried", "Business", "Salaried", "Salaried", "Business",
        "Salaried", "Self-Employed", "Salaried", "Business", "Salaried"
    ],

    "Loan_Status": [
        "Approved", "Approved", "Approved", "Approved", "Rejected",
        "Approved", "Approved", "Rejected", "Approved", "Approved",
        "Approved", "Rejected", "Approved", "Rejected", "Approved",
        "Approved", "Approved", "Rejected", "Approved", "Approved"
    ]
}

df = pd.DataFrame(data)

# 1. Add a new column Annual_Income by multiplying Income by 12.
df["Annual_Income"]=df['Income']*12

# 2. Add a new column Loan_Amount_Lakhs by dividing Loan_Amount by 100000.
df["Loan_Amount_Lakhs"]=df['Loan_Amount']/10000

# 3. Display applicants whose Income is greater than 60000.
print(df[df['Income']>6000])

# 4. Display applicants whose Loan_Amount is greater than 500000.
print(df[df['Loan_Amount']>500000])

# 5. Display applicants whose Credit_Score is greater than 750.
print(df[df['Credit_Score']>750])

# 6. Display applicants whose Loan_Status is "Approved".
print(df[df['Loan_Status']=='Approved'])

# 7. Display only Female applicants.
print(df[df['Gender']=='Female'])

# 8. Display applicants whose Income is less than 50000.
print(df[df['Income']<50000])

# 9. Display applicants whose Loan_Amount is equal to 500000.
print(df[df['Loan_Amount']==500000])

# 10. Display applicants whose Age is greater than 30 AND Loan_Status is "Approved".
print(df[(df["Age"] > 30) & (df["Loan_Status"]=="Approved")])

# 11. Display applicants whose Employment_Type is "Salaried" or he is male
print(df[(df['Employment_Type']=='Salaried')  |  (df['Gender']=='Male')])

# 12. Display applicants whose Loan_Amount is greater than 400000 OR Credit_Score is greater than 780.
print(df[(df['Loan_Amount']>400000)  |  (df['Credit_Score']>780)])

    Loan_ID  Applicant_Name  Age  Gender  Income  Loan_Amount  Loan_Term  \
0      1001    Rahul Sharma   28    Male   45000       250000          5   
1      1002     Priya Verma   35  Female   60000       400000         10   
2      1003      Amit Kumar   42    Male   75000       600000         15   
3      1004      Neha Singh   31  Female   52000       300000          7   
4      1005     Rohan Mehta   29    Male   48000       275000          5   
5      1006    Anjali Gupta   45  Female   90000       800000         20   
6      1007     Vikas Yadav   38    Male   68000       500000         15   
7      1008    Sneha Kapoor   27  Female   42000       200000          5   
8      1009  Arjun Malhotra   33    Male   80000       650000         20   
9      1010      Pooja Jain   40  Female   55000       350000         10   
10     1011     Karan Patel   36    Male   72000       550000         15   
11     1012     Simran Kaur   30  Female   65000       450000         10   
12     1013 

In [ ]:
import pandas as pd
users={"Name":["ajay","sachin","jay","asha","ekta"],
       "Email":["ajay@gmail.com","sachin@gmail.com","jay@gmail.com","asha@gmail.com","ekta@gmail.com"],
       "Password":["ajay123","sachin123","jay123","asha123","ekta123"],
       "Department":["Admin","sales","marketing","sales","billing"],
       "Salary":[20000,40000,70000,8000,10000]}


df=pd.DataFrame(users)

print(df.loc[3])

print(df.loc[1:3])

print(df.loc[3]['Name'])

print(df.loc[2:4][["Name",'Salary']])

Name                    asha
Email         asha@gmail.com
Password             asha123
Department             sales
Salary                  8000
Name: 3, dtype: object
     Name             Email   Password Department  Salary
1  sachin  sachin@gmail.com  sachin123      sales   40000
2     jay     jay@gmail.com     jay123  marketing   70000
3    asha    asha@gmail.com    asha123      sales    8000
asha
   Name  Salary
2   jay   70000
3  asha    8000
4  ekta   10000


In [ ]:
import pandas as pd
users={"Name":["ajay","sachin","jay","asha","ekta"],
       "Email":["ajay@gmail.com","sachin@gmail.com","jay@gmail.com","asha@gmail.com","ekta@gmail.com"],
       "Password":["ajay123","sachin123","jay123","asha123","ekta123"],
       "Department":["Admin","sales","marketing","sales","billing"],
       "Salary":[20000,40000,70000,8000,10000]}


df=pd.DataFrame(users)

df.index=['E101',"E102","E103","E104","E105"]

print(df.loc["E101"])

print(df)

Name                    ajay
Email         ajay@gmail.com
Password             ajay123
Department             Admin
Salary                 20000
Name: E101, dtype: object
        Name             Email   Password Department  Salary
E101    ajay    ajay@gmail.com    ajay123      Admin   20000
E102  sachin  sachin@gmail.com  sachin123      sales   40000
E103     jay     jay@gmail.com     jay123  marketing   70000
E104    asha    asha@gmail.com    asha123      sales    8000
E105    ekta    ekta@gmail.com    ekta123    billing   10000


In [ ]:
import pandas as pd
users={"Name":["ajay","sachin","jay","asha","ekta"],
       "Email":["ajay@gmail.com","sachin@gmail.com","jay@gmail.com","asha@gmail.com","ekta@gmail.com"],
       "Password":["ajay123","sachin123","jay123","asha123","ekta123"],
       "Department":["Admin","sales","marketing","sales","billing"],
       "Salary":[20000,40000,70000,8000,10000]}


df=pd.DataFrame(users)

df=df.sort_values("Name")

print(df)

df=df.sort_values("Name",ascending=False)

print(df)


     Name             Email   Password Department  Salary
0    ajay    ajay@gmail.com    ajay123      Admin   20000
3    asha    asha@gmail.com    asha123      sales    8000
4    ekta    ekta@gmail.com    ekta123    billing   10000
2     jay     jay@gmail.com     jay123  marketing   70000
1  sachin  sachin@gmail.com  sachin123      sales   40000
     Name             Email   Password Department  Salary
1  sachin  sachin@gmail.com  sachin123      sales   40000
2     jay     jay@gmail.com     jay123  marketing   70000
4    ekta    ekta@gmail.com    ekta123    billing   10000
3    asha    asha@gmail.com    asha123      sales    8000
0    ajay    ajay@gmail.com    ajay123      Admin   20000


In [ ]:
import pandas as pd
users={"Name":["ajay","sachin","jay","asha","ekta"],
       "Email":["ajay@gmail.com","sachin@gmail.com","jay@gmail.com","asha@gmail.com","ekta@gmail.com"],
       "Password":["ajay123","sachin123","jay123","asha123","ekta123"],
       "Department":["Admin","sales","marketing","sales","billing"],
       "Salary":[20000,40000,70000,8000,10000]}

df=pd.DataFrame(users)
#df.drop("Password",axis=1,inplace=True)
df1=df.drop("Password",axis=1)   # 1  column   0   row
print(df)
print(df1)

print(df1)

print(df)

df.drop(0,axis=0,inplace=True)  # row remove
print(df)

     Name             Email   Password Department  Salary
0    ajay    ajay@gmail.com    ajay123      Admin   20000
1  sachin  sachin@gmail.com  sachin123      sales   40000
2     jay     jay@gmail.com     jay123  marketing   70000
3    asha    asha@gmail.com    asha123      sales    8000
4    ekta    ekta@gmail.com    ekta123    billing   10000
     Name             Email Department  Salary
0    ajay    ajay@gmail.com      Admin   20000
1  sachin  sachin@gmail.com      sales   40000
2     jay     jay@gmail.com  marketing   70000
3    asha    asha@gmail.com      sales    8000
4    ekta    ekta@gmail.com    billing   10000
     Name             Email Department  Salary
0    ajay    ajay@gmail.com      Admin   20000
1  sachin  sachin@gmail.com      sales   40000
2     jay     jay@gmail.com  marketing   70000
3    asha    asha@gmail.com      sales    8000
4    ekta    ekta@gmail.com    billing   10000
     Name             Email   Password Department  Salary
0    ajay    ajay@gmail.com   

In [ ]:
import pandas as pd
users={"Name":["ajay","sachin","jay","asha","ekta"],
       "Email":["ajay@gmail.com","sachin@gmail.com","jay@gmail.com","asha@gmail.com","ekta@gmail.com"],
       "Password":["ajay123","sachin123","jay123","asha123","ekta123"],
       "Department":["Admin","sales","marketing","sales","billing"],
       "Salary":[20000,40000,70000,8000,10000]}

df=pd.DataFrame(users)
#df.drop("Password",axis=1,inplace=True)
#df1=df.drop("Password",axis=1)   # 1  column   0   row
#print(df)
#print(df1)

#print(df1)

#print(df)

#df.drop(0,axis=0,inplace=True)  # row remove
#print(df)
# multilple column
df1=df.drop(["Password","Email"],axis=1)   # 1  column   0   row
print(df1)
# try remove 2 and 4 row

     Name Department  Salary
0    ajay      Admin   20000
1  sachin      sales   40000
2     jay  marketing   70000
3    asha      sales    8000
4    ekta    billing   10000


In [ ]:
import pandas as pd
customers = {
    "Customer_ID": [101, 102, 103, 104, 105],
    "Customer_Name": ["Rahul", "Priya", "Amit", "Neha", "Rohit"],
    "City": ["Delhi", "Mumbai", "Pune", "Delhi", "Jaipur"]
}
customer_df = pd.DataFrame(customers)

orders = {
    "Order_ID": [1001, 1002, 1003, 1004, 1005, 1006],
    "Customer_ID": [101, 102, 101, 103, 105, 102],
    "Product": ["Laptop", "Mobile", "Mouse", "Keyboard", "Monitor", "Headphones"],
    "Amount": [55000, 30000, 1200, 2500, 15000, 3000]
}
order_df = pd.DataFrame(orders)

print(customer_df)
print(order_df)

Rdf=pd.merge(customer_df,order_df,on="Customer_ID")
print(Rdf)

sdf=pd.merge(customer_df,order_df,on="Customer_ID", how="left")
print(sdf)

tdf=pd.merge(customer_df,order_df,on="Customer_ID", how="right")
print(tdf)

udf=pd.merge(customer_df,order_df,on="Customer_ID", how="outer")
print(udf)

   Customer_ID Customer_Name    City
0          101         Rahul   Delhi
1          102         Priya  Mumbai
2          103          Amit    Pune
3          104          Neha   Delhi
4          105         Rohit  Jaipur
   Order_ID  Customer_ID     Product  Amount
0      1001          101      Laptop   55000
1      1002          102      Mobile   30000
2      1003          101       Mouse    1200
3      1004          103    Keyboard    2500
4      1005          105     Monitor   15000
5      1006          102  Headphones    3000
   Customer_ID Customer_Name    City  Order_ID     Product  Amount
0          101         Rahul   Delhi      1001      Laptop   55000
1          101         Rahul   Delhi      1003       Mouse    1200
2          102         Priya  Mumbai      1002      Mobile   30000
3          102         Priya  Mumbai      1006  Headphones    3000
4          103          Amit    Pune      1004    Keyboard    2500
5          105         Rohit  Jaipur      1005     Monitor   

In [ ]:
import pandas as pd
df1 = pd.DataFrame({
    "Emp_ID": [101, 102, 103],
    "Name": ["Rahul", "Priya", "Amit"],
    "City": ["Delhi", "Mumbai", "Pune"]
})


df2 = pd.DataFrame({
    "Emp_ID": [104, 105, 106],
    "Name": ["Neha", "Ravi", "Sneha"],
    "City": ["Jaipur", "Delhi", "Chennai"]
})

# print(df1)

# print(df2)

df3 = pd.concat([df1, df2], ignore_index=True)

print(df3)

   Emp_ID   Name     City
0     101  Rahul    Delhi
1     102  Priya   Mumbai
2     103   Amit     Pune
3     104   Neha   Jaipur
4     105   Ravi    Delhi
5     106  Sneha  Chennai


In [ ]:
import pandas as pd
users={"Name":["ajay","sachin","jay","asha","ekta"],
       "Email":["ajay@gmail.com","sachin@gmail.com","jay@gmail.com","asha@gmail.com","ekta@gmail.com"],
       "Password":["ajay123","sachin123","jay123","asha123","ekta123"],
       "Department":["Admin","sales","marketing","sales","billing"],
       "Salary":[20000,40000,70000,8000,10000]}
df=pd.DataFrame(users)

df.rename(columns={'Password':'User_Password'},inplace=True)

print(df)

df3=df.rename(columns={'User_Password':'Pass',"Name":"User_Name"})

print(df3)

df.groupby("Department")["Salary"].sum()

     Name             Email User_Password Department  Salary
0    ajay    ajay@gmail.com       ajay123      Admin   20000
1  sachin  sachin@gmail.com     sachin123      sales   40000
2     jay     jay@gmail.com        jay123  marketing   70000
3    asha    asha@gmail.com       asha123      sales    8000
4    ekta    ekta@gmail.com       ekta123    billing   10000
  User_Name             Email       Pass Department  Salary
0      ajay    ajay@gmail.com    ajay123      Admin   20000
1    sachin  sachin@gmail.com  sachin123      sales   40000
2       jay     jay@gmail.com     jay123  marketing   70000
3      asha    asha@gmail.com    asha123      sales    8000
4      ekta    ekta@gmail.com    ekta123    billing   10000


,Salary
Department,
Admin,20000
billing,10000
marketing,70000
sales,48000


In [ ]:
import pandas as pd
data = {
    "Student_ID": range(1, 21),
    "Name": [
        "Aarav", "Priya", "Rahul", "Neha", "Arjun",
        "Sneha", "Vikram", "Ananya", "Rohan", "Kavya",
        "Aditya", "Pooja", "Karan", "Isha", "Manish",
        "Simran", "Varun", "Riya", "Nikhil", "Meera"
    ],
    "Gender": [
        "Male", "Female", "Male", "Female", "Male",
        "Female", "Male", "Female", "Male", "Female",
        "Male", "Female", "Male", "Female", "Male",
        "Female", "Male", "Female", "Male", "Female"
    ],
    "Course": [
        "Python", "Python", "SQL", "SQL", "Python",
        "Power BI", "Python", "SQL", "Power BI", "Python",
        "SQL", "Power BI", "Python", "SQL", "Power BI",
        "Python", "SQL", "Power BI", "Python", "SQL"
    ],
    "City": [
        "Delhi", "Mumbai", "Delhi", "Pune", "Mumbai",
        "Delhi", "Pune", "Delhi", "Mumbai", "Pune",
        "Delhi", "Mumbai", "Pune", "Delhi", "Mumbai",
        "Pune", "Delhi", "Mumbai", "Pune", "Delhi"
    ],
    "Age": [
        21, 22, 20, 23, 21,
        22, 24, 20, 23, 21,
        22, 24, 20, 23, 21,
        22, 24, 20, 23, 22
    ],
    "Marks": [
        85, 78, 92, 67, 88,
        74, 95, 81, 69, 90,
        76, 84, 91, 73, 87,
        79, 94, 72, 89, 80
    ],
    "Fees": [
        50000, 55000, 50000, 45000, 55000,
        60000, 50000, 45000, 60000, 50000,
        45000, 60000, 50000, 45000, 60000,
        50000, 45000, 60000, 50000, 45000
    ]
}
#df = pd.DataFrame(data)
print(df)

# show maximum marks in each subject
print(df.groupby("Course")["Marks"].max())

# count number of MALE and FEMALE  students
print(df.groupby("Gender")["Student_ID"].count())

# show min marks in each Course
print(df.groupby("Course")["Marks"].min())


print(df.groupby("Course")["Marks"].agg(("sum", "min", "max", "count" )))



    Student_ID    Name  Gender    Course    City  Age  Marks   Fees
0            1   Aarav    Male    Python   Delhi   21     85  50000
1            2   Priya  Female    Python  Mumbai   22     78  55000
2            3   Rahul    Male       SQL   Delhi   20     92  50000
3            4    Neha  Female       SQL    Pune   23     67  45000
4            5   Arjun    Male    Python  Mumbai   21     88  55000
5            6   Sneha  Female  Power BI   Delhi   22     74  60000
6            7  Vikram    Male    Python    Pune   24     95  50000
7            8  Ananya  Female       SQL   Delhi   20     81  45000
8            9   Rohan    Male  Power BI  Mumbai   23     69  60000
9           10   Kavya  Female    Python    Pune   21     90  50000
10          11  Aditya    Male       SQL   Delhi   22     76  45000
11          12   Pooja  Female  Power BI  Mumbai   24     84  60000
12          13   Karan    Male    Python    Pune   20     91  50000
13          14    Isha  Female       SQL   Delhi

In [ ]:
import pandas as pd

data = {
    "Order_ID": [101,102,103,104,105,106,107,108,109,110,
                 111,112,113,114,115,116,117,118,119,120],

    "Product": ["Laptop","Mobile","Headphones","Keyboard","Mouse",
                "Laptop","Mobile","Monitor","Tablet","Headphones",
                "Keyboard","Mouse","Laptop","Mobile","Monitor",
                "Tablet","Headphones","Keyboard","Mouse","Laptop"],

    "Category": ["Electronics","Electronics","Accessories","Accessories","Accessories",
                 "Electronics","Electronics","Electronics","Electronics","Accessories",
                 "Accessories","Accessories","Electronics","Electronics","Electronics",
                 "Electronics","Accessories","Accessories","Accessories","Electronics"],

    "City": ["Delhi","Mumbai","Delhi","Pune","Mumbai",
             "Delhi","Bangalore","Pune","Hyderabad","Mumbai",
             "Delhi","Bangalore","Hyderabad","Pune","Delhi",
             "Mumbai","Bangalore","Hyderabad","Pune","Delhi"],

    "Quantity": [2,1,3,2,4,1,2,1,2,3,
                 2,5,1,2,3,1,4,2,3,1],

    "Price": [55000,30000,2000,1500,800,
              60000,28000,22000,35000,2500,
              1800,700,58000,32000,21000,
              36000,2200,1600,750,62000]
}

df = pd.DataFrame(data)

print(df.groupby("City")["Price"].max())

print(df.groupby("Category")["Quantity"].count())

print(pd.pivot_table(df,index="City",columns="Category",values="Price",aggfunc="sum"))        # by default it will take mean values if aggfunc not used

print(pd.pivot_table(df,index="Product", columns="City",values="Quantity", aggfunc="max"))

City
Bangalore    28000
Delhi        62000
Hyderabad    58000
Mumbai       36000
Pune         32000
Name: Price, dtype: int64
Category
Accessories     9
Electronics    11
Name: Quantity, dtype: int64
Category   Accessories  Electronics
City                               
Bangalore         2900        28000
Delhi             3800       198000
Hyderabad         1600        93000
Mumbai            3300        66000
Pune              2250        54000
City        Bangalore  Delhi  Hyderabad  Mumbai  Pune
Product                                              
Headphones        4.0    3.0        NaN     3.0   NaN
Keyboard          NaN    2.0        2.0     NaN   2.0
Laptop            NaN    2.0        1.0     NaN   NaN
Mobile            2.0    NaN        NaN     1.0   2.0
Monitor           NaN    3.0        NaN     NaN   1.0
Mouse             5.0    NaN        NaN     4.0   3.0
Tablet            NaN    NaN        2.0     1.0   NaN
